name: OneJumpAllJump
version: 1.0
main: in.potenfyr.ojaj.OneJumpAllJump
api-version: '1.21'
author: Ashutosh

commands:
  onejump:
    aliases:
      - ojaj

permissions:

  onejump.admin:
    default: op

  onejump.bypass:
    default: false